package com.hp.daily.entity;

public class HpImg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hp_img.id
     *
     * @mbggenerated Sat Nov 09 10:21:52 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hp_img.noteid
     *
     * @mbggenerated Sat Nov 09 10:21:52 CST 2019
     */
    private Integer noteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hp_img.url
     *
     * @mbggenerated Sat Nov 09 10:21:52 CST 2019
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hp_img.id
     *
     * @return the value of hp_img.id
     *
     * @mbggenerated Sat Nov 09 10:21:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hp_img.id
     *
     * @param id the value for hp_img.id
     *
     * @mbggenerated Sat Nov 09 10:21:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hp_img.noteid
     *
     * @return the value of hp_img.noteid
     *
     * @mbggenerated Sat Nov 09 10:21:52 CST 2019
     */
    public Integer getNoteid() {
        return noteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hp_img.noteid
     *
     * @param noteid the value for hp_img.noteid
     *
     * @mbggenerated Sat Nov 09 10:21:52 CST 2019
     */
    public void setNoteid(Integer noteid) {
        this.noteid = noteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hp_img.url
     *
     * @return the value of hp_img.url
     *
     * @mbggenerated Sat Nov 09 10:21:52 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hp_img.url
     *
     * @param url the value for hp_img.url
     *
     * @mbggenerated Sat Nov 09 10:21:52 CST 2019
     */
    public void setUrl(String url) {
        this.url = url;
    }
}