package com.hp.daily.entity;

public class HpUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hp_user.id
     *
     * @mbggenerated Mon Oct 28 08:23:27 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hp_user.name
     *
     * @mbggenerated Mon Oct 28 08:23:27 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hp_user.password
     *
     * @mbggenerated Mon Oct 28 08:23:27 CST 2019
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hp_user.id
     *
     * @return the value of hp_user.id
     *
     * @mbggenerated Mon Oct 28 08:23:27 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hp_user.id
     *
     * @param id the value for hp_user.id
     *
     * @mbggenerated Mon Oct 28 08:23:27 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hp_user.name
     *
     * @return the value of hp_user.name
     *
     * @mbggenerated Mon Oct 28 08:23:27 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hp_user.name
     *
     * @param name the value for hp_user.name
     *
     * @mbggenerated Mon Oct 28 08:23:27 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    public HpUser() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hp_user.password
     *
     * @return the value of hp_user.password
     *
     * @mbggenerated Mon Oct 28 08:23:27 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hp_user.password
     *
     * @param password the value for hp_user.password
     *
     * @mbggenerated Mon Oct 28 08:23:27 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }
}