package com.hp.daily.dao;

import com.hp.daily.entity.HpNote;
import com.hp.daily.entity.HpNoteExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface HpNoteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hp_note
     *
     * @mbggenerated Wed Oct 30 14:42:04 CST 2019
     */
    int countByExample(HpNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hp_note
     *
     * @mbggenerated Wed Oct 30 14:42:04 CST 2019
     */
    int deleteByExample(HpNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hp_note
     *
     * @mbggenerated Wed Oct 30 14:42:04 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hp_note
     *
     * @mbggenerated Wed Oct 30 14:42:04 CST 2019
     */
    int insert(HpNote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hp_note
     *
     * @mbggenerated Wed Oct 30 14:42:04 CST 2019
     */
    int insertSelective(HpNote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hp_note
     *
     * @mbggenerated Wed Oct 30 14:42:04 CST 2019
     */
    List<HpNote> selectByExampleWithBLOBs(HpNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hp_note
     *
     * @mbggenerated Wed Oct 30 14:42:04 CST 2019
     */
    List<HpNote> selectByExample(HpNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hp_note
     *
     * @mbggenerated Wed Oct 30 14:42:04 CST 2019
     */
    HpNote selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hp_note
     *
     * @mbggenerated Wed Oct 30 14:42:04 CST 2019
     */
    int updateByExampleSelective(@Param("record") HpNote record, @Param("example") HpNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hp_note
     *
     * @mbggenerated Wed Oct 30 14:42:04 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") HpNote record, @Param("example") HpNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hp_note
     *
     * @mbggenerated Wed Oct 30 14:42:04 CST 2019
     */
    int updateByExample(@Param("record") HpNote record, @Param("example") HpNoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hp_note
     *
     * @mbggenerated Wed Oct 30 14:42:04 CST 2019
     */
    int updateByPrimaryKeySelective(HpNote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hp_note
     *
     * @mbggenerated Wed Oct 30 14:42:04 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(HpNote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hp_note
     *
     * @mbggenerated Wed Oct 30 14:42:04 CST 2019
     */
    int updateByPrimaryKey(HpNote record);
}